// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuuZ2EKcDa7beoDOnP9uaWLY_dPz7DtTU',
    appId: '1:259113100780:web:1957a360eba603c17c4cc9',
    messagingSenderId: '259113100780',
    projectId: 'e-commerce-dc3cb',
    authDomain: 'e-commerce-dc3cb.firebaseapp.com',
    storageBucket: 'e-commerce-dc3cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAyLaJ3tbB1NynmYyKZKPDEnS5y2XUkgs',
    appId: '1:259113100780:android:3bd18e7265e2ec817c4cc9',
    messagingSenderId: '259113100780',
    projectId: 'e-commerce-dc3cb',
    storageBucket: 'e-commerce-dc3cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGhDs-9A4ikaDs7drxw9z_mYdAF1crfzw',
    appId: '1:259113100780:ios:437621b143ee0fbf7c4cc9',
    messagingSenderId: '259113100780',
    projectId: 'e-commerce-dc3cb',
    storageBucket: 'e-commerce-dc3cb.appspot.com',
    iosBundleId: 'com.example.eCommerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGhDs-9A4ikaDs7drxw9z_mYdAF1crfzw',
    appId: '1:259113100780:ios:1470420ad7f5ebff7c4cc9',
    messagingSenderId: '259113100780',
    projectId: 'e-commerce-dc3cb',
    storageBucket: 'e-commerce-dc3cb.appspot.com',
    iosBundleId: 'com.example.eCommerceProject.RunnerTests',
  );
}
